#-----------------------------------------------------------------#
#  Developer: Aldo Vera-Espinoza                  ___     _______ #
#  Date: Tue May 21 15:50:06 2024                / \ \   / / ____|#
#                                               / _ \ \ / /|  _|  #
#  Project Name: Makefile for GOinterpreter    / ___ \ V / | |___ #
#  Description:                               /_/   \_\_/  |_____|#
#    Makefile for GOinterpreter.                                  #
#-----------------------------------------------------------------#
run:
	@go run .

build:
	go build -v -o testBuild .

clean:
	rm -f testBuild
